services:

    owja_image_proxy.proxy:
        class: Owja\ImageProxyBundle\Service\Proxy

    owja_image_proxy.process:
        class: Owja\ImageProxyBundle\Service\Process

    owja_image_proxy.config:
        class: Owja\ImageProxyBundle\Service\Config