language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=dev-master

cache:
  directories:
    - $COMPOSER_CACHE_DIR

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

before_script:
  - composer selfupdate
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source
